soa/config/routes.rb
Rails.application.routes.draw do
  resources :prices
  resources :accounts
  resources :clients
  resources :users

end

soa/app/models/account.rb
class Account < ActiveRecord::Base
end

soa/app/models/client.rb
class Client < ActiveRecord::Base
end

soa/app/models/price.rb
class Price < ActiveRecord::Base
end

soa/app/models/user.rb
class User < ActiveRecord::Base
end

soa/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:id_client, :yr, :mon, :day, :po, :re, :sold, :price, :tamount, :tcash, :bal, :paid, :rsnum, :prnum, :addbal)
    end
end

soa/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

soa/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:firstname, :lastname, :mi, :address, :pnum, :tnumA)
    end
end

soa/app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_price, only: [:show, :edit, :update, :destroy]

  # GET /prices
  # GET /prices.json
  def index
    @prices = Price.all
  end

  # GET /prices/1
  # GET /prices/1.json
  def show
  end

  # GET /prices/new
  def new
    @price = Price.new
  end

  # GET /prices/1/edit
  def edit
  end

  # POST /prices
  # POST /prices.json
  def create
    @price = Price.new(price_params)

    respond_to do |format|
      if @price.save
        format.html { redirect_to @price, notice: 'Price was successfully created.' }
        format.json { render :show, status: :created, location: @price }
      else
        format.html { render :new }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prices/1
  # PATCH/PUT /prices/1.json
  def update
    respond_to do |format|
      if @price.update(price_params)
        format.html { redirect_to @price, notice: 'Price was successfully updated.' }
        format.json { render :show, status: :ok, location: @price }
      else
        format.html { render :edit }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prices/1
  # DELETE /prices/1.json
  def destroy
    @price.destroy
    respond_to do |format|
      format.html { redirect_to prices_url, notice: 'Price was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price
      @price = Price.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def price_params
      params.require(:price).permit(:price)
    end
end

soa/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fistname, :lastname, :mi, :username, :password, :email, :psec_level_id)
    end
end

soa/app/helpers/accounts_helper.rb
module AccountsHelper
end

soa/app/helpers/application_helper.rb
module ApplicationHelper
end

soa/app/helpers/clients_helper.rb
module ClientsHelper
end

soa/app/helpers/prices_helper.rb
module PricesHelper
end

soa/app/helpers/users_helper.rb
module UsersHelper
end

soa/app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_client %><br>
    <%= f.number_field :id_client %>
  </div>
  <div class="field">
    <%= f.label :yr %><br>
    <%= f.number_field :yr %>
  </div>
  <div class="field">
    <%= f.label :mon %><br>
    <%= f.number_field :mon %>
  </div>
  <div class="field">
    <%= f.label :day %><br>
    <%= f.number_field :day %>
  </div>
  <div class="field">
    <%= f.label :po %><br>
    <%= f.number_field :po %>
  </div>
  <div class="field">
    <%= f.label :re %><br>
    <%= f.number_field :re %>
  </div>
  <div class="field">
    <%= f.label :sold %><br>
    <%= f.number_field :sold %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :tamount %><br>
    <%= f.text_field :tamount %>
  </div>
  <div class="field">
    <%= f.label :tcash %><br>
    <%= f.text_field :tcash %>
  </div>
  <div class="field">
    <%= f.label :bal %><br>
    <%= f.text_field :bal %>
  </div>
  <div class="field">
    <%= f.label :paid %><br>
    <%= f.number_field :paid %>
  </div>
  <div class="field">
    <%= f.label :rsnum %><br>
    <%= f.text_field :rsnum %>
  </div>
  <div class="field">
    <%= f.label :prnum %><br>
    <%= f.text_field :prnum %>
  </div>
  <div class="field">
    <%= f.label :addbal %><br>
    <%= f.number_field :addbal %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

soa/app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

soa/app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Id client</th>
      <th>Yr</th>
      <th>Mon</th>
      <th>Day</th>
      <th>Po</th>
      <th>Re</th>
      <th>Sold</th>
      <th>Price</th>
      <th>Tamount</th>
      <th>Tcash</th>
      <th>Bal</th>
      <th>Paid</th>
      <th>Rsnum</th>
      <th>Prnum</th>
      <th>Addbal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.id_client %></td>
        <td><%= account.yr %></td>
        <td><%= account.mon %></td>
        <td><%= account.day %></td>
        <td><%= account.po %></td>
        <td><%= account.re %></td>
        <td><%= account.sold %></td>
        <td><%= account.price %></td>
        <td><%= account.tamount %></td>
        <td><%= account.tcash %></td>
        <td><%= account.bal %></td>
        <td><%= account.paid %></td>
        <td><%= account.rsnum %></td>
        <td><%= account.prnum %></td>
        <td><%= account.addbal %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

soa/app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

soa/app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id client:</strong>
  <%= @account.id_client %>
</p>

<p>
  <strong>Yr:</strong>
  <%= @account.yr %>
</p>

<p>
  <strong>Mon:</strong>
  <%= @account.mon %>
</p>

<p>
  <strong>Day:</strong>
  <%= @account.day %>
</p>

<p>
  <strong>Po:</strong>
  <%= @account.po %>
</p>

<p>
  <strong>Re:</strong>
  <%= @account.re %>
</p>

<p>
  <strong>Sold:</strong>
  <%= @account.sold %>
</p>

<p>
  <strong>Price:</strong>
  <%= @account.price %>
</p>

<p>
  <strong>Tamount:</strong>
  <%= @account.tamount %>
</p>

<p>
  <strong>Tcash:</strong>
  <%= @account.tcash %>
</p>

<p>
  <strong>Bal:</strong>
  <%= @account.bal %>
</p>

<p>
  <strong>Paid:</strong>
  <%= @account.paid %>
</p>

<p>
  <strong>Rsnum:</strong>
  <%= @account.rsnum %>
</p>

<p>
  <strong>Prnum:</strong>
  <%= @account.prnum %>
</p>

<p>
  <strong>Addbal:</strong>
  <%= @account.addbal %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

soa/app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :mi %><br>
    <%= f.text_field :mi %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :pnum %><br>
    <%= f.text_field :pnum %>
  </div>
  <div class="field">
    <%= f.label :tnumA %><br>
    <%= f.text_field :tnumA %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

soa/app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

soa/app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Clients</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Mi</th>
      <th>Address</th>
      <th>Pnum</th>
      <th>Tnuma</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.firstname %></td>
        <td><%= client.lastname %></td>
        <td><%= client.mi %></td>
        <td><%= client.address %></td>
        <td><%= client.pnum %></td>
        <td><%= client.tnumA %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

soa/app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

soa/app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @client.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @client.lastname %>
</p>

<p>
  <strong>Mi:</strong>
  <%= @client.mi %>
</p>

<p>
  <strong>Address:</strong>
  <%= @client.address %>
</p>

<p>
  <strong>Pnum:</strong>
  <%= @client.pnum %>
</p>

<p>
  <strong>Tnuma:</strong>
  <%= @client.tnumA %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

soa/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Soa</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

soa/app/views/prices/_form.html.erb
<%= form_for(@price) do |f| %>
  <% if @price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@price.errors.count, "error") %> prohibited this price from being saved:</h2>

      <ul>
      <% @price.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

soa/app/views/prices/edit.html.erb
<h1>Editing Price</h1>

<%= render 'form' %>

<%= link_to 'Show', @price %> |
<%= link_to 'Back', prices_path %>

soa/app/views/prices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Prices</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prices.each do |price| %>
      <tr>
        <td><%= price.price %></td>
        <td><%= link_to 'Show', price %></td>
        <td><%= link_to 'Edit', edit_price_path(price) %></td>
        <td><%= link_to 'Destroy', price, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Price', new_price_path %>

soa/app/views/prices/new.html.erb
<h1>New Price</h1>

<%= render 'form' %>

<%= link_to 'Back', prices_path %>

soa/app/views/prices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @price.price %>
</p>

<%= link_to 'Edit', edit_price_path(@price) %> |
<%= link_to 'Back', prices_path %>

soa/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fistname %><br>
    <%= f.text_field :fistname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :mi %><br>
    <%= f.text_field :mi %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :psec_level_id %><br>
    <%= f.text_field :psec_level_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

soa/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

soa/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Fistname</th>
      <th>Lastname</th>
      <th>Mi</th>
      <th>Username</th>
      <th>Password</th>
      <th>Email</th>
      <th>Psec level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.fistname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.mi %></td>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td><%= user.psec_level_id %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

soa/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

soa/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fistname:</strong>
  <%= @user.fistname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Mi:</strong>
  <%= @user.mi %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Psec level:</strong>
  <%= @user.psec_level_id %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>